### ISSUE TITLE
Validator: fails on a valid (?) CellML file

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#296] opened 2019-04-04 03:59 UTC
I believe [this CellML file](https://github.com/agarny/test-cellml-files/blob/master/cellml-2.0/algebraic_eqn_derivative_on_rhs_one_component.cellml) to be valid (?!), yet libCellML can't validate it. Here are the errors it reports (just the description):
- Namespace prefix cellml for units on cn is not defined.
- Math cn element has an invalid attribute type 'cellml:units' in the cellml namespace.
- CellML identifiers must contain one or more basic Latin alphabetic characters.
- Math cn element with the value '1' does not have a valid cellml:units attribute.
- Namespace prefix cellml for units on cn is not defined.
- No declaration for attribute cellml:units of element cn.

Is it "normal" for this file to fail at this stage?...

**Comment by hsorby** [comment] 2019-04-04 09:33
Ah yes it is, the namespace prefix is not being carried forward from the document declaration. The MathML is taken in isolation so it misses the xmlns:cellml.  That needs fixing.

**Comment by agarny** [comment] 2019-04-04 19:22
Thanks, @hsorby, the messages make more sense to me now. (It's just that I want to validate a model before actually generating code for it. Makes the process much easier when we know that a model is valid, especially when it comes to its math.)

**Comment by nickerso** [comment] 2019-04-05 01:59
duplicate of #175.

**Closed as completed by nickerso** 2019-04-05 01:59 UTC
