### ISSUE TITLE
Handle simple algebraic model a + b = c + d

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#900] opened 2021-07-05 23:38 UTC
We want to be able to handle the simple algebraic model `a+b=c+d` where we will look too generate code suitable for a root solver.  We would not be looking to manipulate this equation into a suitable form for a direct solution.

**Comment by agarny** [comment] 2021-07-05 23:42
Duplicate of issue #882.

**Closed as completed by agarny** 2021-07-05 23:42 UTC
