### ISSUE TITLE
Default profile for generator

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#508] opened 2020-01-07 09:22 UTC
Hi @agarny 

I thought I'd read somewhere that the default profile for generation was C (and of course now I can't find it...), but when running in Python it's using the Python profile by default.  Which is the intended behaviour?

- default is *always* C, no matter the language used to generate it, or
- the generating language implies the default profile?

Thanks :)

**Comment by agarny** [comment] 2020-01-07 20:02
The default profiler is or, rather, should always be C (see [here](https://github.com/cellml/libcellml/blob/8c5d921ccc3904f2b17d4ffe52001601485ad7f3/src/api/libcellml/generatorprofile.h#L56)).

So, if from Python, the default profile generator is Python (and not C) then there is a problem with our bindings.

(FWIW, I am not sure we could easily, if at all, use the binding language as the default profiler.)

**Comment by kerimoyle** [comment] 2020-01-07 20:09
OK, then in that case I think there's an issue with the bindings.  I'm now getting a Python default in the python file (which I don't think used to happen? My tutorial which used to work suddenly didn't today, and this was the cause) and C default in the C++ file (which was present before).

**Comment by agarny** [comment] 2020-01-07 20:18
So, a recent PR would have broken things in that regards? Strange, I wonder what could have done that. Either way, it would be nice if you could create an issue (or maybe update this one) with some Python code for reproducing it.

**Comment by kerimoyle** [comment] 2020-01-07 20:28
I wonder if it's to do with the use of the `create()` function setting the default profile?  In Python I've just been calling the constructor directly as `generator = Generator()`, but in C++ use create()?  Examples (which as far as I can recall worked before Christmas ... ) are here:
[C++ file](https://github.com/kerimoyle/libcellml/blob/pr344_documentation/docs/tutorials/tutorial3/tutorial3_complete.cpp) (which seems fine)
[Python one ](https://github.com/kerimoyle/libcellml/blob/pr344_documentation/docs/tutorials/tutorial3/tutorial3_complete.py
) (which doesn't work because default is now python, so section 4.d doesn't work as expected)

**Comment by agarny** [comment] 2020-01-07 20:32
The `create()` method only create a shared instance of `Generator`. So, its purpose is only to make things "easier" (and more consistent) for the end user. So, I wouldn't expect that to be the cause of our problem. Anyway, I am going to try to have a look at it...

**Comment by kerimoyle** [comment] 2020-01-07 20:34
But is that where the default gets set?  I couldn't find it when I looked earlier.  If we're setting the profile only in the `create()` function, which doesn't get called in Python, then that could be the cause?  I'll have another look in the morning :)

**Comment by agarny** [comment] 2020-01-07 21:02
Oops, my bad! You are completely right. I was looking at the `Generator::create()` method. Doh! The `GeneratorProfile::create()` method does indeed specify the default profiler as being the C profiler. Ok, we need to do something about it and we ought to check our other `create()` methods too, to make sure that we don't have something else that is similar for our bindings.

**Comment by agarny** [comment] 2020-01-07 21:17
Closing this issue in favour of issue #510, which is more generic. Thanks @kerimoyle for spotting and reporting the issue!

**Closed as completed by agarny** 2020-01-07 21:17 UTC
