### ISSUE TITLE
CMake: make sure that ClangFormat is of the expected version

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#946] opened 2021-07-26 06:16 UTC
On Windows, I have (through MSVC) ClangFormat 6 installed and upon configuring libCellML, I am allowed to format the code (i.e. do something like `ninja format_code`) and this results in ClangFormat complaining about the options in our `.clang-format` file. This is understandable since we expect ClangFormat 11+.

So, we should only create the `format_code` target if ClangFormat 11+ is available.

**Comment by nickerso** [comment] 2021-07-26 10:50
duplicate of #356

**Comment by nickerso** [comment] 2021-07-26 10:53
also worth noting the discussion on #411 whereby Visual Studio does magic based on the presence of a `.clang-format` file regardless of the target. Is that still applicable?

**Comment by agarny** [comment] 2021-07-26 12:43
> duplicate of #356

Hmm, indeed.



> also worth noting the discussion on #411 whereby Visual Studio does magic based on the presence of a `.clang-format` file regardless of the target. Is that still applicable?

No idea, I don't use VS...

**Closed as completed** 2021-08-16 22:16 UTC
