### ISSUE TITLE
Importer: allow a path without a trailing slash when calling `resolveImports()`

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#678] opened 2020-08-05 03:53 UTC
See https://github.com/cellml/libcellml/pull/608#issuecomment-668964644.

**Comment by nickerso** [comment] 2020-08-05 04:22
Closing this as a duplicate of #592.

**Closed as completed by nickerso** 2020-08-05 04:22 UTC

**Comment by agarny** [comment] 2020-08-05 04:26
Oopsie! :)
