### ISSUE TITLE
Improve Importers ability to handle base directory

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#872] opened 2021-06-08 23:45 UTC
Currently the `Importer` base directory must end in a trailing slash.  The documentation on `resolveImports` does not mention this fact.  Either the documentation needs to be updated or fix the code to detect trailing slash and add one if there is not one present.

**Comment by agarny** [comment] 2021-06-08 23:49
I would definitely fix the code. After all, both `cd /my/path` and `cd /my/path/` work, and that's what people are used to.

**Comment by nickerso** [comment] 2021-06-09 00:26
duplicate of #592 ?

**Comment by agarny** [comment] 2021-06-09 00:28
> duplicate of #592 ?

Indeed.

**Closed as completed** 2021-06-09 03:17 UTC
