### ISSUE TITLE
Equivalent variables: cycles, interfaces, and name convention?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#295] opened 2019-04-02 09:11 UTC
See **19.10.5**: No cycles permitted in the variable equivalence network.  Currently the validator does not catch the cyclical definition created in the TEST(Validator, validateInvalidConnections) test:
```
    libcellml::Variable::addEquivalence(v1_1, v2);    // cycle? created between v1_1, v2, v3
    libcellml::Variable::addEquivalence(v1_2, v2);
    libcellml::Variable::addEquivalence(v1_1, v3);    // cycle? created between v1_1, v2, v3
    libcellml::Variable::addEquivalence(v1_1, v4);
    libcellml::Variable::addEquivalence(v2, v3);       // cycle? created between v1_1, v2, v3
    libcellml::Variable::addEquivalence(v1_1, v3);    // duplicate, skips silently
```
I figure we can test this in the Validator::validateModel function, but wondered whether it should also be checked/prevented in the Variable::addEquivalence function too?

The specifications talk about "connections" and "map_variables" but the code talks about "equivalent variables".  I presume that "mapping" a variable to another the same as making them "equivalent", or are there more subtleties there?

**Comment by nickerso** [comment] 2019-04-02 16:40
We want to ensure that users of the API are able to create the models they need to create without continually ensuring they have a valid model. For example, when modifying a model there could be many times when the model will be invalid, but we only want to check for a valid model when requested.

We have also tried to develop the libCellML data model to align with what we see as the underlying CellML data model, rather than the XML serialisation. So, yes, the variable equivalences are what capture the information also represented by the connections in the XML serialisation. Perhaps the only subtlety is that there is (I think) a bit of code tracking when equivalences originate from the same connection element in parsing the XML, and we need some way to track id's in case users have annotated the connection/map_variable elements.

**Comment by kerimoyle** [comment] 2019-04-02 16:56
Ok, thanks, I think I've got it.  I'd missed the significance of the bit which said that there was only one connection pair allowed between components - that makes it all a lot simpler.  Getting there (slowly!).  I'll leave this issue open until the cycle validation is added.

**Comment by kerimoyle** [comment] 2019-04-03 19:27
Equivalent variables unit testing is working, including nested units and arbitrary powers.  It returns the mismatch in base units where they don't match - needs a tidy around error messages and for speed.  
But I noticed that the specs (19.10.6 and .7) say that multipliers don't need to match ... is that true when the model is validated too?  ie: we'll permit models with equivalent variables with different prefixes or multipliers? mm + cm is ok?

**Comment by nickerso** [comment] 2019-04-03 20:22
yep - mismatched multipliers are fine in connections. Also true for validation. The spec only requires unit conversion across connections, bot within math. When we get to validating the math we will want to be able to check for consistency of units within an equation, but this is not a validation error for CellML. It would be a "warning" or similar.

**Comment by agarny** [comment] 2019-04-03 20:42
Nice progress @kerimoyle. I wanted to check the code (as we/I do, as we go along), but noticed a couple of things that make it difficult to do so:
- No tabs. Use 4-space indentations instead (see [here](https://github.com/kerimoyle/libcellml-keri/commit/2dcaf2f3eb28ea1a82220c7215b6be87c0084a88#diff-17c437c531d5aaa85235f337bea7ecb2R692) and [here](https://github.com/kerimoyle/libcellml-keri/commit/2dcaf2f3eb28ea1a82220c7215b6be87c0084a88#diff-17c437c531d5aaa85235f337bea7ecb2R944) for example).
- No trailing spaces (see [here](https://github.com/kerimoyle/libcellml-keri/commit/6072b81f801580dc98d49757a57573bb90e1bf62#diff-bd8f167953cc43fb7cba7d420fbd1d48R276) and [here](https://github.com/kerimoyle/libcellml-keri/commit/6072b81f801580dc98d49757a57573bb90e1bf62#diff-bd8f167953cc43fb7cba7d420fbd1d48R365) for example).

Also, for consistency:
- Use `TODO` rather than `__TODO__` (see [here](https://github.com/kerimoyle/libcellml-keri/commit/2dcaf2f3eb28ea1a82220c7215b6be87c0084a88#diff-17c437c531d5aaa85235f337bea7ecb2L43) and [here](https://github.com/kerimoyle/libcellml-keri/commit/2dcaf2f3eb28ea1a82220c7215b6be87c0084a88#diff-17c437c531d5aaa85235f337bea7ecb2R1157) for example).
- Use infinitives in comments, i.e. `Check...` rather than `Checks...` (see [here](https://github.com/kerimoyle/libcellml-keri/commit/2dcaf2f3eb28ea1a82220c7215b6be87c0084a88#diff-17c437c531d5aaa85235f337bea7ecb2L904) and [here](https://github.com/kerimoyle/libcellml-keri/commit/2dcaf2f3eb28ea1a82220c7215b6be87c0084a88#diff-17c437c531d5aaa85235f337bea7ecb2R988) for example).

**Comment by kerimoyle** [comment] 2019-04-03 21:02
Thanks Alan, there's still a lot of tidying up to do!  I used the
underscores in the todo because it formats the doxygen file that I refer
to, but will remove them. Ditto the comments, most will disappear as
they're for my benefit as I figure out what's going on.  I'll follow your
formatting from here on though, thanks :)

**Comment by kerimoyle** [comment] 2019-04-04 19:02
Hi again all
- Cycle detection for mapped variables is working but needs more tests to go with it (I've done them on paper and it will scale for bigger networks and more than one loop).  https://github.com/kerimoyle/libcellml-keri/commit/98ed4b312055ccb32dc5f17e50312a3e262cb9e4 

- The test is currently failing and I need advice on best practice here: My validator returns an error with the closed list of variables which are cyclically defined, which changes each time I run the tests (presumably related to how the pointers are stored?):
![image](https://user-images.githubusercontent.com/46887220/55580910-f2c15200-571b-11e9-98e2-f2a78c7f9a3b.png)
So ... I can change the error message to exclude the variables (which kinda defeats its purpose) or change the test to only look at the start of the error message (which also kinda defeats _its_ purpose), or do something more complicated ... but before doing that I wanted to check if there was some agreed pattern for these kind of things?

- @agarny I tried out the VS Windows version of Clang but need to understand the option flags better before I let it go automagically (I managed to mangle a whole lot of stuff this morning!).  The latest commit will have the same issues as earlier but they will be fixed soon ... :)

**Comment by agarny** [comment] 2019-04-04 20:01
- Tests must be reproducible and the kind of message you are currently generating for your cyclic variables issue looks good to me. So, I would do whatever it takes to ensure that your code always generates the same error message in that kind of situation. I haven't looked at your code, but I would expect that there has to be a way to get things to work you want. :)
- When you are talking about Clang on Windows, are you talking about using Clang as a compiler in place of MSVC or are you indirectly talking about Clang-Tidy (see issue #283 and PR #288)? If the former, then I think we probably want to stick to MSVC on Windows (even though libCellML still ought to build fine using Clang, as it does on macOS). If the latter, then I wouldn't worry about Clang-Tidy on Windows. Right now, the idea is to have Clang-Tidy check things on macOS in our CI system. This being said, nothing prevents you from having Clang-Tidy installed on your development machine, and see what it spits out. However, wait for PR #288 to be merged in since it contains all the flags that we want to support (we may refine things as we god, but I reckon the current set should be a good starting point). What is pretty certain, I think is that we don't want to leave it to Clang-Tidy to fix things for us automatically. We still want to remain in control, if need be.

**Comment by nickerso** [comment] 2019-04-05 02:33
In CellML models (that are least somewhat valid), `component_name` + `variable_name` gives a unique identifier for any variable in a model (we often use `component_name/variable_name`) - this would provide a potentially more useful error message.

I know that @hsorby had another test or two that wasn't reproducible, likely due to the same issue of how we store lists of child objects. I seem to recall in that one he simply tested against all the possible combinations, but I guess this would have lots more possible combinations :) I wonder if rather than trying to force the error to always come out the same, we get a bit "smarter" in our testing since we should know in the test what cycles should exist. I'm thinking that you could parse the error string and just check that all the expected variables are present?

**Comment by agarny** [comment] 2019-04-05 02:39
> I wonder if rather than trying to force the error to always come out the same, we get a bit "smarter" in our testing since we should know in the test what cycles should exist. I'm thinking that you could parse the error string and just check that all the expected variables are present?

I don't think we want that. Some users of libCellML might have libCellML-related tests of their own, so we don't want them to have to rely on "tricks" to account for libCellML's possible "shortcomings". I mean, we are all about reproducibility, right?... :)

**Comment by kerimoyle** [comment] 2019-04-05 07:02
The test is reproducible in that, given the same set of data, it will show the same result.  In that way it does everything that a test should do.  The trouble is in giving it the same set of data each time.  I can certainly write tests which account for things like loops of a starting place but correct order, and don't think that that's really a trick or a shortcoming in libcellml.  It was more a question of whether testing a string comparison of the error messages was the only way of validating a test.  Any libCellML users who write tests of their own will have the same understanding (certainly if we mention it in the docs somewhere) in order to create and interpret their tests anyway...

Related to that, there were a couple of bits of information which might help both reproducibility and navigating through the models that I haven't found yet:
- when we store a variable as the child of a component, is there any hook in the Variable to the parent Component?  I considered passing everything around the validation as a VariablePtr,ComponentPtr pair but figured there must be a better way ... ?
- is there any kind of accessible (ie: not just an address) static id generated for each/any of the elements when they're created?  Eg can I create three variables called "a", "b", "c", and retreive them by some kind of global index to variables, or immutable id for each (ie: not their component/name combo)?

Finally, the clang that I've been playing with excluded compilation, it was just two different flavours of plugin/extension for VS for text formatting.  Somewhere in the running it changed functional bits of the code (putting in semicolons and brackets etc) which was less than helpful.  I'll check the settings and see how it goes, but would only use it for making sure that my code is as similar as possible to that written on your macs :)

**Comment by kerimoyle** [comment] 2019-04-05 13:16
I've created a more taxing test for cycles.  The validator will find ones which are embedded or adjacent (eg: a-b-c-a and b-c-d-b), and returns at least one of the three cycles (a-b-c-a; b-c-d-b; and a-b-c-d-a).  Cycles are tested for and will pass if the variables are present in the two loops reported.  It currently only returns the variable name though.

There's another mechanism that I'm not sure about.  Do we allow sibling variables in a component to be equivalent to the same variable in another component?  
- component 1 contains v1_1 and v1_2; 
- component 2 contains v2; 
- v1_1 equivalent to v2; 
- v1_2 equivalent to v2.
Thoughts?

**Comment by nickerso** [comment] 2019-04-05 17:10
> when we store a variable as the child of a component, is there any hook in the Variable to the parent Component? I considered passing everything around the validation as a VariablePtr,ComponentPtr pair but figured there must be a better way ... ?

There is the `void *Entity::getParent()` method for getting the parent component, but see #193.

> Do we allow sibling variables in a component to be equivalent to the same variable in another component?

Interesting. Currently I believe that we do, and I know that I have used this myself in actual models - e.g., to set multiple parameters to the same numeric value, or having two potentially different `time` variables that "temporarily" get set to the global `time` during model development. This is straightforward in CellML 1.x where the interfaces define a direction and it was easy to check these connections make sense. For CellML 2.0 it is less clear how to check this and maybe it is allowed but could result in a valid model that can't be instantiated into procedural code? Need to check the spec draft and see if it covers this case....

**Comment by agarny** [comment] 2019-04-05 19:46
> The test is reproducible in that, given the same set of data, it will show the same result. In that way it does everything that a test should do. The trouble is in giving it the same set of data each time. I can certainly write tests which account for things like loops of a starting place but correct order, and don't think that that's really a trick or a shortcoming in libcellml. It was more a question of whether testing a string comparison of the error messages was the only way of validating a test. Any libCellML users who write tests of their own will have the same understanding (certainly if we mention it in the docs somewhere) in order to create and interpret their tests anyway...

What do you mean exactly by "The trouble is in giving it the same set of data each time"? Are you saying that the input to your test varies from one run to another?

Validation of a model may result in error strings being generated. So, for me, testing those strings should definitely be part of validating a test, and those strings should always be the same given the same input.

If a test generates an error string related to an `a <-> b <-> c <-> a` loop, then every time I run that test, I would expect that test to reference that `a <-> b <-> c <-> a` loop. If, for some reasons, the test was to reference a `b <-> c <-> a <-> b` loop, then I would consider that test to have failed (even though the loop is indeed the same). (Sorry if I am stating the obvious...)

**Comment by kerimoyle** [comment] 2019-04-05 21:58
Thanks @nickerso ... that's what I was after.  Even if it's changed to another type in the future I presume there will always be a parent pointer of some kind - I'll add a component name to the variables returned with errors.

Re the loop testing, it's not stating the obvious (I hope) as I still don't quite understand, sorry...  
If I create a model during the test and duplicate the call to validateModel several times in a row _in the same test_, the error messages are identical, presumably because the way that the variables are stored is the same between each call to the validator.  The loops are found with the same starting node (variable in this case) and reported a-b-c-a each time (for example).
```
start test
generate model
validate model
print error (a-b-c-a)
validate model
print error (a-b-c-a)
validate model
print error (a-b-c-a)
end test
```
... all report the loop in the same order.


If I do not alter the code or the model it generates at all but re-run the test (ie: same model but different instance of it) I get the same loop member variables identified, though perhaps in a different order (b-c-a-b for example).  
```
start test
generate model
validate model
print error (b-c-a-b)
end test

start test
generate model 
validate model
print error (a-b-c-a)
end test
```
... so it prints the same loop contents but the order may be different.  I'd thought this was because of the pointer storage somewhere being different in each instance, but if there's a way that users can specify more precisely how their models are constructed please can you let me know?  

I'd thought that:
- first, that in an undirected network (because the variable maps go both ways?) these two loops are identical? (Or if not, what determines which node comes first in the overall description?); 
- and secondly, that for the purposes of checking that a CellML file was valid, just checking that the network was loop-free was all that was needed.  I only added the extra part to report on the loop(s)' contents and to help the user debug their model.  

As the tests stand at the moment, the network to be checked has 17 nodes (variables) with branches and two loops.  Both loops are identified and their contents listed in the error messages.  I've said that the test passes if both loops identify the nodes involved correctly, but I don't specify which nodes they need to start with (mostly because I don't know which the correct one would be anyway?).

I feel like we're talking at cross purposes because I'm really missing something here ...?

**Comment by hsorby** [comment] 2019-04-08 20:28
The sort of problem that you are having here is probably due to the underlying traversal being non-deterministic. This I find is something that you just have to deal with.  The way to deal with this non-deterministic behaviour varies on a case by case basis.

In this case I think the correct way to test if the loop is detected correctly or not is to test for the length of the loop and to test the set of variables is exactly the set you expect.  The order or starting point isn't actually significant and I think it is right not to define a test that expects a specific order/starting point.

**Comment by agarny** [comment] 2019-04-09 03:13
> In this case I think the correct way to test if the loop is detected correctly or not is to test for the length of the loop and to test the set of variables is exactly the set you expect. The order or starting point isn't actually significant and I think it is right not to define a test that expects a specific order/starting point.

I disagree with that, but I am also in favour of democracy (damn! :)), so... I shall leave it to the popular vote. :)

Quickly going back to @kerimoyle's example, I would expect the same error message to be generated when running different instances of the same test, i.e.

```
start test
generate model
validate model
print error (a-b-c-a)
end test

start test
generate model 
validate model
print error (a-b-c-a)
end test
```

That's what I mean by reproducible tests. I want the output to always be the same given the exact same input. Otherwise, I can't see why the underlying traversal would be non-deterministic, but then again I haven't had a proper look at the code. I would think that the memory address being different in different instances of the test would be the reason for the different outputs.

**Comment by hsorby** [comment] 2019-04-09 03:20
I'm happy to go with autocracy if I'm in charge :)

**Comment by nickerso** [comment] 2019-04-09 03:27
The test is 100% reproducible, the same validation error is produced every time. The default serialisation of that error to a string will change due to the use of unordered lists to store the data inside the API.

If anything, the issue is really about how we are trying to overload a single string with lots of information. Being able to retrieve a much richer error description would enable tool developers to present the errors in the manner most helpful to their users.

**Comment by agarny** [comment] 2019-04-09 03:39
> The test is 100% reproducible, the same validation error is produced every time. The default serialisation of that error to a string will change due to the use of unordered lists to store the data inside the API.

Ok, so we agree that "the default serialisation of that error to a string" is not reproducible. :)

> If anything, the issue is really about how we are trying to overload a single string with lots of information. Being able to retrieve a much richer error description would enable tool developers to present the errors in the manner most helpful to their users.

Probably the way to go, I would agree.

**Comment by kerimoyle** [comment] 2019-04-10 12:55
> It would be a "warning" or similar.

@nickerso Are warnings (cf errors) issued elsewhere? Are the messages only for the user's benefit (cf preventing code from running later or something)?  If they are just hints to how to fix invalid models, then warnings should use the same mechanism (the Error struct)?

**Comment by nickerso** [comment] 2019-04-10 14:00
I'm not sure if we have a plan yet for dealing with warnings from the validator. I think you are right that it should be using the same Error mechanism, but perhaps we should add a severity property or similar?

But for now, we probably want to focus on validating against the specification, so only worry about errors. Thoughts @hsorby  @agarny @MichaelClerx ?

**Comment by hsorby** [comment] 2019-04-10 19:05
Yes - to only concerning ourselves with validating against the specification.

**Comment by agarny** [comment] 2019-04-10 21:16
Agreed that, at this stage, we probably only want to validate against the specification. Then, at some point, we could have warnings, etc., in which case I would agree with @nickerso about having a severity property or something like that.

**Closed as completed** 2019-09-05 04:49 UTC
